### Numpy library

In [ ]:
# It is a library that helps us deal with array datatype.

# 1. Collection of elements very similar to lists but with important differences
# 2. Homogenous (unlike lists which are heterogenous)
# 3. Offers very simple syntax to process the elements of the array and efficient processing. 
# 4. The way the data is stored is different in arrays and lists. 
# 5. Iterable
# 6. Subscriptable
# 7. Ordered
# 8. Nested lists can be of different sizes. Arrays cannot.

In [1]:
import numpy as np

In [7]:
lst1 = [1,'a', 2+3j, None, True, False]

print(lst1)

[1, 'a', (2+3j), None, True, False]


In [14]:
arr1 = np.array([1,'a', 2+3j, None, True, False])

print(arr1)
print(arr1.dtype)



[1 'a' (2+3j) None True False]
object


In [15]:
print(arr1/2)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [8]:
lst1 = range(10000000)

print(len(lst1))

10000000


In [9]:
arr1 = np.array(range(10000000))
print(len(arr1))

10000000


In [10]:
print(len(lst1) == len(arr1))

True


In [11]:
%%time

lst2 = [x*2 for x in lst1]

Wall time: 892 ms


In [12]:
%%time

arr2 = arr1 * 2

Wall time: 23.3 ms


In [24]:
lst1 = [[1,2,3,4], [10,20,30,40, 50]]

print(lst1)

[[1, 2, 3, 4], [10, 20, 30, 40, 50]]


In [25]:
arr1 = np.array(lst1)

print(arr1)

[list([1, 2, 3, 4]) list([10, 20, 30, 40, 50])]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13332\3255359961.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array(lst1)


In [23]:
# 2 x 4 matrix

In [20]:
print(len(arr1))

2


In [40]:
arr1 = np.arange(48).reshape(2,2,3,4)
print(arr1)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


In [ ]:
# 1st example

axis0 = 4

# 2nd example (3,4)

axis 0 = 3
axis 1 = 4

# 3rd example (2,3,4)

axis 0 = 2
axis 1 = 3
axis 2 = 4

# 4th example (5,2,3,4)

axis 0 = 5
axis 1 = 2
axis 2 = 3
axis 3 = 4


In [41]:
lst1 = [[1,2,3,4], [5,6,7,8]]



[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]


In [42]:
arr1 = np.arange(1,9).reshape(2,4)

print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
print(arr1*2)

[[ 2  4  6  8]
 [10 12 14 16]]


In [51]:
arr2 = np.array([[10,20,30,40], [50, 60,70,80]])

print(arr1)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[10 20 30 40]
 [50 60 70 80]]


In [50]:
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (2,4) (2,5) 

In [46]:
print(arr1**2)

[[ 1  4  9 16]
 [25 36 49 64]]


In [47]:
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [48]:
print(arr1[0][3])

4


In [56]:
print(arr1[:,3])

[4 8]


In [ ]:
arr1

In [58]:
arr1 = np.arange(120).reshape(2,3,4,5)

print(arr1)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [ ]:
#2*3*4*5

In [70]:
print(arr1[0,1:,2:,1:3])

[[[31 32]
  [36 37]]

 [[51 52]
  [56 57]]]


In [85]:
# Assignment

arr1 = np.arange(24).reshape(2,3,4)

print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [86]:
arr1[0,2,3] = 100

print(arr1)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10 100]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [87]:
arr1[0,1] = 99

print(arr1)

[[[  0   1   2   3]
  [ 99  99  99  99]
  [  8   9  10 100]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [89]:
arr1[1,1:,0] = 101

print(arr1)

[[[  0   1   2   3]
  [ 99  99  99  99]
  [  8   9  10 100]]

 [[ 12  13  14  15]
  [101 101  18  19]
  [101 101  22  23]]]


In [90]:
arr1[1] = 1001

print(arr1)

[[[   0    1    2    3]
  [  99   99   99   99]
  [   8    9   10  100]]

 [[1001 1001 1001 1001]
  [1001 1001 1001 1001]
  [1001 1001 1001 1001]]]


In [91]:
arr1[1,1:,1] = [2001,3001]

print(arr1)

[[[   0    1    2    3]
  [  99   99   99   99]
  [   8    9   10  100]]

 [[1001 1001 1001 1001]
  [1001 2001 1001 1001]
  [1001 3001 1001 1001]]]


In [ ]:
# item assignment - we are replacing one element with one element. 

# slice assignment - on arrays:
# either supply a scalar(single value) which will be used for ALL the elements being replaced
# OR give same number of elements TO replace and same number of elements replacing them.

In [ ]:
# list slice assignment?

# 1. items replacing the existing ones - must be put in an iterable. 
# 2. The number of items being replaced did not have to match the number of items replacing them.

In [59]:
print(arr1[-1,-2])

[[80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [66]:
print(arr1[1,1,:3,2:])

[[82 83 84]
 [87 88 89]
 [92 93 94]]


In [27]:
print(arr1.dtype)

int32


In [28]:
print(arr1.ndim)

1


In [29]:
print(arr1.shape)

(4,)


In [75]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(0,60,10).reshape(2,3)

print(arr1)
print('-'*125)
print(arr2)
print('-'*125)
print(arr1+arr2)

[[0 1 2]
 [3 4 5]]
-----------------------------------------------------------------------------------------------------------------------------
[[ 0 10 20]
 [30 40 50]]
-----------------------------------------------------------------------------------------------------------------------------
[[ 0 11 22]
 [33 44 55]]


In [78]:
arr1 = np.array([1,2,3,4], dtype = str)

print(arr1)
print(arr1.dtype)

['1' '2' '3' '4']
<U1


### Boolean indexing - see main notebook

### Broadcasting

In [2]:
import numpy as np

scalararr = np.arange(1,2).reshape(1,1,1)

print(scalararr)

[[[1]]]


In [3]:
scalararr2 = np.arange(1,3).reshape(2,1,1)

print(scalararr2)

[[[1]]

 [[2]]]


In [11]:
np.random.seed()
arr1 = np.random.randint(1,10,24).reshape(2,3,4)

print(arr1)

[[[1 7 1 8]
  [2 2 1 3]
  [9 8 1 7]]

 [[7 1 9 6]
  [2 7 8 7]
  [7 5 7 2]]]


In [24]:
np.random.seed()

arr2 = np.random.randint(1,10,12).reshape(3,1,4)

print(arr2)

[[[2 2 8 7]]

 [[3 8 4 5]]

 [[4 9 9 8]]]


In [25]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,3,4) (3,1,4) 