### Numpy (Numerical Python) Library

In [ ]:
# NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data
# structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python. 
# NumPy contains, among other things:

# ● A fast and efficient multidimensional array object ndarray
# ● Functions for performing element-wise computations with arrays or mathematical
# operations between arrays
# ● Tools for reading and writing array-based datasets to disk
# ● Linear algebra operations, Fourier transform, and random number generation
# ● A mature C API to enable Python extensions and native C or C++ code to access

In [ ]:
# NumPy’s data structures and computational facilities.

# Beyond the fast array-processing capabilities that NumPy adds to Python, one of its primary uses in data analysis is as a
# container for data to be passed between algorithms and libraries.

# For numerical data, NumPy arrays are more efficient for storing and manipulating data than the other built-in Python
# data structures. Also, libraries written in a lower-level language, such as C or Fortran, can operate on the data stored
# in a NumPy array without copying data into some other memory representation. Thus, many numerical computing tools for
# Python either assume NumPy arrays as a primary data structure or else target seamless interoperability with NumPy.

In [ ]:
# Why Numpy?
# One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on
# large arrays of data. There are a number of reasons for this:
# ● NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s
# library of algorithms written in the C language can operate on this memory without any type checking or other overhead. 
# NumPy arrays also use much less memory than built-in Python sequences.
# ● NumPy operations perform complex computations on entire arrays without the need for Python for loops. To give you an
# idea of the performance difference, consider a NumPy array of one million integers, and the equivalent Python list:

In [ ]:
lst1 = [1,'a', 2+3j, (2,3)]

print(lst1)

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array(list('abcde'))

print(arr1)
print(arr2)

In [ ]:
print(arr1.dtype)

In [ ]:
print(arr2.dtype)

In [ ]:
arr3 = np.array(lst1)

print(arr3)

print(arr3.dtype)

In [ ]:
array is a collection of homogenous data.

arrays can have n dimensions

In [ ]:
lst1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

print(lst1)

In [ ]:
arr1 = np.array(lst1)

print(arr1)

In [ ]:
import numpy as np

arr1 = np.arange(10)

print(arr1)

In [ ]:
arr2 = arr1 +1

print(arr2)

In [ ]:
lst1 = list(range(10))

print(lst1)
print(type(lst1))

In [ ]:
for x in range(len(lst1)):
    lst1[x] = lst1[x]+1

print(lst1)

In [ ]:
import numpy as np

arr1 = np.array(range(10))

print(arr1)
print(type(arr1))

In [ ]:
lst1 = [1,2,'a', 2+3j, None, 10.2]

print(lst1)
print(type(lst1))

In [ ]:
arr1 = np.array(lst1)

print(arr1)
print(type(arr1))
print(arr1.dtype)

In [ ]:
arr2 = np.array(range(10))

print(arr2)
print(type(arr2))
print(arr2.dtype)

In [ ]:
import numpy as np

nump_a = np.arange(10000000)
list_a = list(range(10000000))

print(len(nump_a), type(nump_a))

print(len(list_a), type(list_a))

In [ ]:
import numpy as np

nump_a = np.arange(10000000)
list_a = list(range(10000000))

print(len(nump_a))

print(len(list_a))

In [ ]:
%%time

list_b = [x*2 for x in list_a]

In [ ]:
%%time

nump_a2 = nump_a * 2

In [ ]:
nump_b = np.arange(10)
list_b = list(range(10))

nump_m = nump_b * 2

In [ ]:
list_c = list_b*2

In [ ]:
list_d = [x*2 for x in list_b]

print(nump_m, type(nump_m))
print(list_c, type(list_c))
print(list_d, type(list_d))

In [ ]:
lst1 = [[1,2,3],[2,3], [4,5,6,7]]

print(lst1)

In [ ]:
# The NumPy ndarray
# A Multidimensional Array Object One of the key features of NumPy is its N-dimensional array object, or ndarray, which is
# a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole
# blocks of data using similar syntax to the equivalent operations between scalar elements.

In [ ]:
# Numpy stands for Numerical Python

# Arrays - 

# 1. Homogenous data
# 2. In contiguous blocks of memory
# 3. Faster than pythons lists
# 4. Easier syntax for arithmetic operations (no need for loops)



In [ ]:
arr1 = np.arange(1,10,2)

print(arr1)
print(type(arr1))
print(arr1.dtype)

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([5,7,9,12])

print(arr1)

In [ ]:
lst1 = tuple(range(10))

print(lst1)

In [ ]:
arr1 = np.array(lst1)

print(arr1)
print(type(arr1))

In [ ]:
for x in range(len(lst1)):
    lst1[x] += 5
    
    
print(lst1)

In [ ]:
arr1 = np.arange(5)

In [ ]:
arr1 = arr1 + 5

print(arr1)

In [ ]:
lst1 = [list(range(1,11)), list(range(11,21))]

print(lst1)

In [ ]:
arr1 = np.array(lst1)

print(arr1)

In [ ]:
for x in range(len(lst1)):
    for y in range(len(lst1[x])):
        lst1[x][y] += 5
        
        
print(lst1)

In [ ]:
arr1 = arr1+5

print(arr1)

In [ ]:
print(dir(np))

In [ ]:
data = np.arange(720).reshape(2,3,4,5,6)

print(data)
#print(len(data))
print(data.shape)
print(data.ndim)

In [ ]:
Axis no.            Elements
0                   2

0,1                 3x2

0,1,2               4x3x2

0,1,2,3             5x4x3x2





In [ ]:
str1 = 'CAP'

In [ ]:
print(data.shape)
print(data.ndim)

In [ ]:
print(data.size)

In [ ]:
arr1 = np.arange(6).reshape(3,2)

print(arr1)
print(arr1.shape)
print(arr1.ndim)

In [ ]:
arr1[2][1]

In [ ]:
arr1 = np.array([1,2,3])

print(arr1.shape)
print(arr1.ndim)

In [ ]:
data = data * 10

print(data)

In [ ]:
data1 = np.random.randint(1,10,24)

print(data1)

In [ ]:
data2 = np.random.randint(1,10,24).reshape(4,6)
print(data2)

In [ ]:
# Note the appearance is of a 3 layer nested list. However, though they appear the same - these are arrays!! Important :
# note NO commas between the elements of the array. 

print(type(data))

for x in range(len(data)):
    for y in range(len(data[x])):
        for z in range(len(data[x][y])):
            print(data[x][y][z])
            
# The 3 dimensional array object is constructed of : 4 elements in each row, 3 rows nested in the 2nd dimension of the 
# array object and 2 such 2nd Dimension arrays nested in the outer most array block. 

In [ ]:
print(data)

In [ ]:
print(data * 10)

In [ ]:
# Note, we have not changed the original data ndarray.
print(data)

# We could change the original data variable by assigning the result to itself or to a new variable as usual.

In [ ]:
data1 = data*10

print(data1)

In [ ]:
data = np.random.randint(1,10,10)


print(data)

In [ ]:
data[2] = 77

print(data)

In [ ]:
data = np.arange(1,16).reshape(3,5)
data1 = np.arange(10,160,10).reshape(3,5)
print(data)
print(data1)

In [ ]:
print(data)

In [ ]:
print(data1)

In [ ]:
# Easily perform arithmetic operations between same shaped/sized arrays. 

# However, there is also 'broadcasting' for arrays that are not the same shape. These follow certain rules. 

In [ ]:
print(data+data1)

In [ ]:
data = np.arange(120).reshape(2,3,4,5)

print(data)

In [ ]:
dataaxis0 = data.sum(axis=2)


print(dataaxis0)

In [ ]:
data1 = np.arange(101,107).reshape(2,3)

print(data1)

In [ ]:
data3 = data+data1

print(data3)

In [ ]:
arr5D = np.random.randint(1,100,720).reshape(2,3,4,5,6)

print(arr5D)

In [ ]:
arr5D[0,1,1,1,2]

In [ ]:
arr = np.random.randint(1,100,6)

print(arr)
print(arr.shape)
print(arr.ndim)

In [ ]:
arr2d = np.random.randint(1,100,30).reshape(5,6)

print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

In [ ]:
6 - 1D
0

5,6 - 2D
0,1

4,5,6 - 3D
0,1,2

In [ ]:
index numbers of each element of each n dim array is different

index numbers of axes is different

In [ ]:
arr3d = np.random.randint(1,100,120).reshape(4,5,6)

print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)

In [ ]:
print(arr3d[0,:,:1])

In [ ]:
arr4d = np.arange(360).reshape(3,4,5,6)

print(arr4d)
print(arr4d.shape)
print(arr4d.ndim)

In [ ]:
print(data)

In [ ]:
arr

In [ ]:
data2 = data.reshape(3,2,4)

print(data2)

In [ ]:
print(data + data2)

In [ ]:
data1 = data*10

print(data1)

In [ ]:
data1 = data1+data1
print(data1)

In [ ]:
print(type(data1[0][0][0]))

In [ ]:
print(data1.dtype)`

In [ ]:
arralpha = np.array(list('abcde'), dtype = str)

print(arralpha)
print(type(arralpha))
print(arralpha.dtype)

In [ ]:
arr1 = np.array([1,2,3,4], dtype = float)

print(arr1)
print(arr1.dtype)

In [ ]:
print(data1.shape)

In [ ]:
onedarr = np.arange(6).reshape(2,3)

print(onedarr.shape)

In [ ]:
# An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same
# type. 

lst1 = ['a', 100, (20,30), {'x':10, 'y':20}]

np_arr = np.array(lst1)

print(np_arr)
print(np_arr.dtype)

In [ ]:
print(np_arr)
print(np_arr.dtype)

print(type(np_arr[2]))

In [ ]:
lst1 = list(range(10))

print(lst1)

In [ ]:
np_arr = np.array(lst1,dtype = float)


print(np_arr)

In [ ]:
print(np_arr.dtype)

In [ ]:
# Unless explicitly specified, np.array tries to infer a good data type for the array that it creates.

In [ ]:
int1 = (2*100)
tup1 = (2,)
tup2 = 2,
print(type(int1))
print(type(tup1))
print(type(tup2))
print(len(tup1), len(tup2))

In [ ]:
lst2 = [2, 300, 72, 34, 78,10.2, '100', '1000', (2)]
np_arr = np.array(lst2)

print(np_arr)
print(np_arr.dtype)

In [ ]:
lstalpha = [1,2,3,4]

print(lstalpha)

In [ ]:
np_str = np.array(lstalpha, dtype = str)

print(np_str)
print(type(np_str[0]))
print(type(np_str))

In [ ]:
print(np_arr)
print(np_arr.dtype)


for x in np_arr:
    print(type(x))

In [ ]:
lst3 = [2.13, 7.272, 3, 4.321, 11.234, 101]

np_arr2 = np.array(lst3)

print(np_arr2)
print(np_arr2.dtype)

print(type(np_arr2[2]))

In [ ]:
import numpy as np

lst11 = [[1,2,3,4], [10,20,30,40]]

np_arr11 = np.array(lst11,dtype = int)

print(np_arr11)
print(type(np_arr11[0,0]))
print(np_arr11[0,0])


In [ ]:
np_arr = np.random.randint(1,100,48).reshape(3,2,2,4)
print(np_arr)

In [ ]:
4 - 0 axis
2,4 - 1 axis
3,2,4 - 2 axis
5,3,2,4 - 3 axis

In [ ]:
print(np_arr.shape)

In [ ]:
print(np_arr.ndim)

In [ ]:
np_arr_rs = np_arr.reshape(2,2,3,4)
print(np_arr_rs)
print(type(np_arr_rs))

In [ ]:
# Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data
# type of the array:

print(np_arr_rs.shape)

In [ ]:
print(np_arr_rs.dtype)

In [ ]:
print(np_arr_rs.ndim)

In [ ]:
# Creating ndarrays The easiest way to create an array is to use the array function. This accepts any sequence-like object
# (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good
# candidate for conversion:

lst1 = [1,2,3,4]

nump_arr = np.array(lst1)

print(nump_arr)
print(type(nump_arr))
print(nump_arr.shape)
print(f'Dimensions of nump_arr is {nump_arr.ndim}.')

In [ ]:
image_rec = np.random.randint(0,256,48).reshape(3,4,4)


print(image_rec)

In [ ]:
# Note, how for a one dimensional array, the shape tuple is (4,) but the dimensions are 1.

In [ ]:


nump_arr = np.arange(8).reshape(4,2)

print(nump_arr.shape)
print(nump_arr.ndim)
print(nump_arr)

In [ ]:
# Nested sequences, like a list of equal-length lists, will be converted into a multi-dimensional array:

In [ ]:
lst2 = [[1,2,3,4], [10,20,30,40]]

nump_arr2 = np.array(lst2)

print(nump_arr2)
print(type(nump_arr2))
print(nump_arr2.shape)
print(f'Dimensions of nump_arr2 is {nump_arr2.ndim}.')

In [ ]:
print(dir(np))

In [ ]:
print(nump_arr2)
nump_arr2

In [ ]:
# Note the output when outputting nump_arr2 on the notebook. It specifies that this is an array - but note the return of the
# comma!! It doesnt make a difference since we know that this is an array but just pointing out the difference in the 
# view of both commands.

In [ ]:
# What are arrays?

# Representation of collection of homogenous data.

# Continuous block of memory how arrays store the data and metadata making them faster to process. 
# Arrays allow us to perform operations on the whole array without running a loop like in python iterables. 


# Axes of arrays.

# np.array to create arrays from iterables. 



In [ ]:
lst1 = [1,2,3,4]

print(lst1)

In [ ]:
import numpy as np

arr1 = np.array(lst1, dtype = str)


print(arr1)
print(arr1.dtype)

### Basic Indexing and Slicing

In [ ]:
#NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual
# elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [ ]:
import numpy as np

arr1 = np.arange(120).reshape(4,5,6)
print(arr1)

In [ ]:
arr1[2,3,4:]

In [ ]:
arr1[1][3][5]

In [ ]:
arr1[1,3,5]

In [ ]:
arr1[1:3,1:3,2:4]

In [ ]:
# axes are also integer indexed
# elements on each axes are also integer indexed

In [ ]:
print(arr1[5])

In [ ]:
print(arr1[2:4])

In [ ]:
arr1 = np.arange(72).reshape(4,6,3)

print(arr1)

In [ ]:
print(arr1[2])

In [ ]:
print(arr1)

In [ ]:
print(arr1[:2,1:4, -2:])

In [ ]:
# Slice assignment

In [ ]:
lst1 = [1,2,3,4,5]

lst1[1:4] = 12,13,14
print(lst1)

In [ ]:
# 1. That the assigned values should be in an iterable
# 2. The number of elements being replaced do not have to have the same lenght as the len of elements replacing.

In [ ]:
arr1 = np.array([1,2,3,4,5])

print(arr1)

In [ ]:
arr1[2:4] = 12


print(arr1)

In [ ]:
arr1[1:4] = 12,13,14

print(arr1)

In [ ]:
arr1 = np.arange(12).reshape(4,3)


print(arr1)

In [ ]:
arr1[1:3,1:]

In [ ]:
arr1[1:3, 1:] = np.array([[44,55],[77,88]])

In [ ]:
arr2 = np.array([[44,55],[77,88]])

In [ ]:
arr2

In [ ]:
arr1[1:3,1:] = 100

In [ ]:
arr1

In [ ]:
arr1

In [ ]:
print(arr1+5)

In [ ]:
arr1 = np.arange(3).reshape(1,1,3)


print(arr1)
print(arr1.shape)

In [ ]:
# 1. That the assigned values should be in an iterable
# 2. The number of elements being replaced do not have to have the same lenght as the len of elements replacing.

In [ ]:
# For lists the elements in the slice of list being replaced do not need to be equal in length to the elements replacing them.

In [ ]:
arr1 = np.arange(24).reshape(2,3,4)

arr1

In [ ]:
arr2 = np.arange(48).reshape(4,3,4)

arr2

In [ ]:
arr1+arr2

In [ ]:
arr1 = np.arange(10)



In [ ]:
print(arr1)

In [ ]:
print(arr1[2:7])

In [ ]:
# Slice assignment in arrays

# 1. Either assign a scalar value which will replace each one of the elements sliced. 

# 2. Give same length of values to replace and to be replaced

In [ ]:
arr1[2:7] = 11,12,13,14,15

print(arr1)

In [ ]:
list1 = list(range(10))
print(list1)
list1[2:4] = 11,
print(list1)

In [ ]:
# As you can see, if you assign a scalar value to a slice of an array, as in arr[2:4] = 11, the value is propagated (or 
# broadcasted henceforth) to the entire selection. While for lists, the value(s) of the iterable replace(s) the slice.

In [ ]:
# An important first distinction from Python’s built-in lists is that array slices are views on the original array. This
# means that the data is not copied, and any modifications to the view will be reflected in the source array. To give
# an example of this, first create a slice of arr:

In [ ]:
lst1 = list(range(10))

lst2 = lst1[2:6]

print(lst1)
print(lst2)


In [ ]:
lst2[0] = 20

print(lst1)
print(lst2)

In [ ]:
arr = np.arange(11)
arr_slice = arr[5:8]
print(arr)
print(arr_slice)

In [ ]:
arr_slice[0] = np.array([1,2,3,4])
print(arr)
print(arr_slice)

In [ ]:
arr[6] = 686

print(arr)
print(arr_slice)

In [ ]:
print(id(arr))
print(id(arr_slice))

In [ ]:
list1 = list(range(11))
lst_slice = list1[5:8]
print(list1)
print(lst_slice)


In [ ]:
lst_slice[1] = 6789
print(lst_slice)
print(list1)

In [ ]:
lst1 = list(range(10))
lst2 = lst1[:]

print(lst1)
print(lst2)

In [ ]:
# To copy an array or its slice you have to exlicitly copy.

In [ ]:
arr = np.arange(11)
print(arr)
arr_slice = arr[5:8].copy()

print(arr_slice)

In [ ]:
arr_slice[0] = 555

print(arr_slice)
print(arr)

In [ ]:
# Accessing values in nested arrays.

In [ ]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

print(lst1[1][1])

In [ ]:
arr_hdim = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_hdim)

In [ ]:
print(arr_hdim[1,2])

In [ ]:
arr1 = np.random.randint(1,100,24).reshape(2,3,4)

print(arr1)

In [ ]:
# Numpy allows you to use easier syntax to access elements in nested arrays.

print(arr1[1,0:2,1:])

In [ ]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

print(lst1[1][1])


In [ ]:
print(lst1[-1,-1])

In [ ]:
#Indexing with slices

#Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

arr = np.arange(11)
arr

In [ ]:
print(arr[1:6])

In [ ]:
# Consider a two-dimensional array. Slicing this array is a bit different:
 
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr_2d)

In [ ]:
(3,3)

In [ ]:
print(arr_2d[:2,:2])

In [ ]:
print(arr_2d[:2,:2])

In [ ]:
import numpy as np

In [ ]:
np_i = np.arange(1,61).reshape(5,4,3)
print(np_i)

In [ ]:
print(np_i[1,:,:2])

# arr_2d[0, 1]
# arr_2d[:2,:]

In [ ]:
np_i[:2,:,1:]

In [ ]:
# As we see, the array has been sliced on axis 0

In [ ]:
print(arr_2d)

In [ ]:
# As the syntax for multiple indexes seen previously, we can pass multiple slices as well. 

print(arr_2d[:2])

In [ ]:
print(arr_2d[:2, :2])

In [ ]:
arr_2d

In [ ]:
# or

print(arr_2d[:2,1:])

In [ ]:
# When slicing like this, you always obtain array views of the same number of dimensions

In [ ]:
# By mixing integer indexes and slices, you get lower dimensional slices

In [ ]:
arr_3d = np.arange(60).reshape(3,5,4)

print(arr_3d)

In [ ]:
print(arr_3d[1,1:, 1:4])

In [ ]:
# Here we first selected the 1st index on axis 0 and then sliced from 1st index to end along axis 1

In [ ]:
# Another example, slice from 1st index to end along axis 0 and then index 2 along axis 1
print(arr_2d[1:])

In [ ]:
print(arr_2d[1:,2])

In [ ]:
arr_3d = np.arange(24).reshape(2,3,4)

print(arr_3d)

In [ ]:
print(arr_3d[1][1][2])

In [ ]:
print(arr_3d[1:,:2,0])

In [ ]:
# Numpy

# np.array function to create arrays
# nested arrays, shapes of arrays, axes, dimensions of arrays. 
# Indexing, slicing, assignment arrays. 
# Arithmetic operatons on arrays using scalars or array with array operations.

In [ ]:
import numpy as np
arr1 = np.arange(24).reshape(2,3,4)
arr2 = np.arange(4).reshape(4,1)

In [ ]:
arr3 = np.arange(4)

print(arr3)
print(arr3.shape)

In [ ]:
print(arr2)
print(arr2.shape)

In [ ]:
arr1+arr2

In [ ]:
arr4 = np.arange(12).reshape(1,4,3)

print(arr4)

### Boolean Indexing

In [ ]:
# Let’s consider an example where we have some data in an array and an array of names with duplicates. 

In [ ]:
print(120*100)

In [ ]:
import numpy as np

arr1 = np.arange(10)

print(arr1)

In [ ]:
print(arr1*100)

In [ ]:
print(120>100)

In [ ]:
print(arr1>5)

In [ ]:
import numpy as np
arr1 = np.array([101,120,39,421,75,1001])

print(arr1)

In [ ]:
print(20+1)

In [ ]:
print(arr1+1)

In [ ]:
print(20>10)

In [ ]:
print(arr1>100)

In [ ]:
arr1[arr1>100]

In [ ]:
names = np.array(['Bob', 'John', 'Steve', 'Will', 'Bob', 'Steve', 'Bob'])
print(names)

In [ ]:
# Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with
# the string 'Bob' yields a boolean array:
print(names == 'Bob')

In [ ]:
names_bool = names == 'Bob'

print(names_bool)

In [ ]:
data = np.random.choice(np.arange(1,100),7, replace = False)

print(data)

In [ ]:
print(data[names_bool])

[73 57 82 71 9 15 54]

[T F F F T F T]

73- - - 9 - 54

In [ ]:
import numpy as np

In [ ]:
data = np.arange(24).reshape(4,3,2)

In [ ]:
print(data)

In [ ]:
names_bool = np.array([True, False, False, True])

print(names_bool)

In [ ]:
#axis index and element index

In [ ]:
data[names_bool]

In [ ]:
data[1, :, names_bool]

In [ ]:
data[1,:,names_bool] # True False False False True False True

In [ ]:
14, 18,  20
21, 25, 27

In [ ]:
7,3,2
0 1 2

: 

In [ ]:
data[:, 1,0]

In [ ]:
data = np.random.randint(1,10,49).reshape(7,7)

In [ ]:
print(data)

In [ ]:
print(names_bool)

In [ ]:
data[names_bool]

In [ ]:
arr1 = np.arange(4).reshape(4)

print(arr1)
print(arr1.shape)
print(arr1.ndim)

In [ ]:
arr2 = np.arange(12).reshape(3,4)

print(arr2)
print(arr2.shape)
print(arr2.ndim)

In [ ]:
arr3 = np.arange(24).reshape(2,3,4)


print(arr3)
print(arr3.shape)
print(arr3.ndim)

In [ ]:
4
0 1D = 1 Index position axis

3,4
0,1   2D = 2 Index postions

2,3,4
0,1,2 3D = 3 index positions for axis

In [ ]:
arr1 = np.random.randint(1,100,24).reshape(2,3,4)


print(arr1)

In [ ]:
np_range = np.arange(len(names_bool))

print(np_range)

In [ ]:
print(np_range[names_bool])

In [ ]:
print(data[names_bool])

In [ ]:
print(data)

In [ ]:
data[:,:3]

In [ ]:
# We can use the values from the boolean array returned from the comparison operator == performed on 'names' array to 
# index from another array data.

In [ ]:
print(data)

In [ ]:
print(data[:,names_bool])

In [ ]:
print(data[:,2:4])

In [ ]:
print(data[:, names_bool])

In [ ]:
print(names)
print(names=='Bob')

In [ ]:
print('Bob'=='Bob')

In [ ]:
print(names=='Bob')


In [ ]:
names_bool = names == 'Bob'

print(names_bool)
print(type(names_bool))

In [ ]:
data1 = data[2]

print(data1)

In [ ]:
print(names_bool)

In [ ]:
print(data1[names_bool])

In [ ]:
lst1 = list('abcdefg')

lst2 = []

for x in lst1:
    for y in range(len(lst1)):
        lst2.append(x*(y+1))
print(lst2)

In [ ]:
arr_alpha = np.arange(1,50).reshape(7,7)

print(arr_alpha)

In [ ]:
print(names_bool)

In [ ]:
print(arr_alpha[2:5, names_bool])

In [ ]:
print(data)

In [ ]:
data1 = np.random.randint(1,10,42).reshape(2,7,3)

print(data1)

In [ ]:
print(names)

In [ ]:
print(names_bool)

In [ ]:
print(data1[:,names_bool])

In [ ]:
print(data)

In [ ]:
print(data1)

In [ ]:
data2 = data1.reshape(2,7,3)

print(data2)


In [ ]:
print(data2[:,names=='Bob', :])

In [ ]:
#asarray

In [ ]:
print(nump_arr2)

In [ ]:
nump_arr2[1,2] = 33

print(nump_arr2)

In [ ]:
nump_mIdx = np.random.randint(1,10,72).reshape(3,2,3,4)

print(nump_mIdx)

In [ ]:
nump_mIdx[1][1][1][1] = 88

print(nump_mIdx)

In [ ]:
nump_mIdx[2][0][0][3] = 606

print(nump_mIdx)

In [ ]:
import numpy as np

lst1 = [1,2,3,4]
np_array = np.array(lst1)
np_asarray = np.asarray(lst1)

print(np_array)
print(type(np_array))

print(np_asarray)
print(type(np_asarray))

In [ ]:
lst1[0] = 100

print(lst1)
print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 101
print(lst1)
print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 1
print(np_array)

In [ ]:
np_asarray[0] = 1001

print(lst1)
print(np_array)
print(np_asarray)


###### np.array from list - change to either list or array does not affect the other
###### np.asarray from list - change to either list or array does not affect the other

##### np.array from array - change to either array does not affect the other
##### np.asarray from array - change to either DOES affect the other

In [ ]:
lst2 = [1,2,3,4]

np_lst = np.array(lst2)

print(np_lst)
print(type(np_lst))

In [ ]:
np_array_lst = np.array(np_lst)
np_asarray_lst = np.asarray(np_lst)

print(np_array_lst, type(np_array_lst))
print(np_asarray_lst, type(np_asarray_lst))

In [ ]:
np_lst[0] = 1001

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
print(id(np_lst))
print(id(np_array_lst))
print(id(np_asarray_lst))

In [ ]:
np_array_lst[0][0] = 1111

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
np_asarray_lst[1] = 2222

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
# Before we go on - lets make the axis of Numpy clear. 
import numpy as np

arr = np.arange(1,25)

print(arr)

In [ ]:
arr1 = arr.reshape(2,3,4)

print(arr1)

In [ ]:
arrsum1 = arr1[0]+arr1[1]

print(arrsum1)

In [ ]:
print(np.sum(arr1))

In [ ]:
print(np.sum(arr1,axis = 2))

In [ ]:
2,3,4   

axis 0 = 3,4

axis 1 = 2,4

axis 2 = 2,3


In [ ]:
arrx = np.arange(1,25)
arrx


In [ ]:
arr2 = arrx.reshape(2,3,4)
print(arr2)

In [ ]:
print(np.sum(arr2))

In [ ]:
axis0 = np.sum(arr2, axis = 0)

print(axis0)
print(axis0.shape)

In [ ]:
axis1 = np.sum(arr2, axis = 1)

print(axis1)
print(axis1.shape)

In [ ]:
print(arr2)

In [ ]:
axis2 = np.sum(arr2, axis = 2)


print(axis2)
print(axis2.shape)

In [ ]:
arrnew = np.arange(1,121).reshape(2,3,4,5)

print(arrnew)

In [ ]:
axis3 = np.sum(arrnew, axis = 3)

print(axis3)
print(axis3.shape)

In [ ]:
print('arr :', arr, '\n','_'*125)
print('arr1 :', arr1, '\n','_'*125)
print('arr2 :', arr2, '\n','_'*125)

In [ ]:
arr2 = arr.reshape(2,3,4)
print('arr2 :', arr2, '\n','_'*125)


In [ ]:
arr3 = arr.reshape(2,4,3)
print(arr3)

In [ ]:
arr4 = arr.reshape(4,3,2)
print(arr4)

In [ ]:
print(arr)

In [ ]:
print('Sum Arr', np.sum(arr, axis = 0)) # 1D Array has no axis 1.

In [ ]:
arr4 = arr.reshape(2,3,4)

In [ ]:
print(arr4)
print(arr4.shape)

In [ ]:
print(np.sum(arr4, axis = 2))
print(np.sum(arr4, axis = 2).shape)

In [ ]:
# In built function sum will sum on 0 axis by default. 
# np.sum will sum all axis elements together by default i.e. if no axis specified.

In [ ]:
print(np.sum(arr4))

In [ ]:
print('sum Axis 0', np.sum(arr4, axis = 0))

In [ ]:
print(arr4)

In [ ]:
ax0 = np.sum(arr4, axis = 0)

print(ax0)
print(ax0.shape)

In [ ]:
print(arr4)
print(arr4.shape) 

In [ ]:
print(arr4)

In [ ]:
arr_col = np.sum(arr4, axis = 1)
print(arr_col)
print(arr_col.shape)

In [ ]:
print(arr4)

In [ ]:
print('Sum Axis 2', np.sum(arr4, axis = 2)) # 4,3,2     - 4,3

In [ ]:
4, 3

In [ ]:
arr6 = np.arange(1,13).reshape(3,2,2)

print(arr6)

In [ ]:
arr = np.arange(1,49)
arr5 = arr.reshape(3,4,2,2)
print('arr5 :', arr5)
print('Sum Axis 3', np.sum(arr5, axis = 0))

In [ ]:
print(np.sum(arr6,axis = 2))

In [ ]:
print(np.sum(arr6, axis = 1))

In [ ]:
print(np.sum(arr6))

In [ ]:
import numpy as np

num_arr = np.arange(1,5.5, 0.2)

print(num_arr)
print(type(num_arr))

In [ ]:
python_range = list(range(1,20,0.2))
print(python_range)

### Homogeneous n-dimensional vectors:

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape(using tuples for shape).

In [ ]:
import numpy as np

np_zero = np.zeros(10, dtype = int)

print(np_zero)

In [ ]:
np_zero6x2 = np.zeros([2,3,4])

print(np_zero6x2)

In [ ]:
#Note above how the shape is a tuple. 

In [ ]:
np_one = np.ones(10)
print(np_one)

In [ ]:
np_one6x2 = np.ones((2,3,4), dtype = int)

print(np_one6x2)

In [ ]:
np_full_5 = np.full(10,5)

print(np_full_5)

In [ ]:
np_full_a = np.full(10, 'a')

In [ ]:
print(np_full_a)

In [ ]:
np_fullshape = np.full((2,3,4), 'Hi')

print(np_fullshape)

In [ ]:
x = np.array([2,3], dtype = object)

print(x)

In [ ]:
np_full6x2_5 = np.full((2,3,4), fill_value = np.array([x,x,x,x]))

print(np_full6x2_5)

In [ ]:
# Empty creates an array without initializing its values to any particular value. To create a higher dimensional array
# with these methods, use a tuple for shape.

In [ ]:
np_nan = np.full(10,None)

print(np_nan)

print(type(np_nan[0]))

In [1]:
import numpy as np

np_empty = np.empty(10)
print(np_empty)

[ 4.82406556e+228  1.34104863e-110  7.30927250e-114  8.79467787e-313
  4.37300893e-308  3.76155539e+199  8.38752460e+242  2.53352367e-309
  6.01347002e-154 -2.36070100e-310]


In [2]:
np_empty6x2 = np.empty((2,6))
print(np_empty6x2)

[[8.83286916e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000
  6.23058367e-307 5.39746319e-062]
 [1.72295699e+184 1.77109152e-051 7.79330907e-043 2.70248092e-056
  1.64725679e+185 1.43369838e+161]]


In [ ]:
#Note that the numpy empty does not actually have empty values - it does create the array of desired shape and size but with
# arbitary values. It is slightly faster to initialise than np.zeros and np.ones especially for larger arrays. 

#### Note that for each of np.zeros, np.ones, np.full and np.empty there are np.zeros_like, ones_like, full_like and empty_like which behave just like the difference between np.array and np.asarray i.e. if the matrix is already an array, then does not create a copy but just gives array like funcitonality.

In [ ]:
#Matrix Functions

In [5]:
#1. The identity matrix:
# In linear algebra, the identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros
# elsewhere.

np_id = np.identity(5, dtype = bool)

print(np_id)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [ ]:
# Note that by default the 1s and 0s are float type. 

In [6]:
np_id_int = np.identity(5, dtype = int)

print(np_id_int)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
np_id_bool = np.identity(5,dtype= bool)

print(np_id_bool)

In [7]:
# 2. Function ‘eye’:
# It is used to return a 2-D array with ones on the diagonal and zeros elsewhere. Unlike identity, array does not necessarily
# have to be square.

np_eye_1 = np.eye(5, dtype = int)

print(np_eye_1)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:
np_eye_5x4 = np.eye(5,4, dtype = int, k=-1)

print(np_eye_5x4)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# We can also specify the diagnol in the eye function unlike the identity function. 0 is the default, Positive values are
# integers above the main diagonal and negative values are integers below the main diagonal. 

In [16]:
np_eye_8x6_0 = np.eye(6,6,-1, dtype= int)

print(np_eye_8x6_0)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [ ]:
np_eye_8x6_p1 = np.eye(8,6,1)

print(np_eye_8x6_p1)

In [ ]:
np_eye_8x6_p2 = np.eye(6,6,2)

print(np_eye_8x6_p2)

In [ ]:
np_eye_8x6_n1 = np.eye(6,6,-1)

print(np_eye_8x6_n1)

In [ ]:
np_eye_8x6_n2 = np.eye(6,6,-2)

print(np_eye_8x6_n2)

In [ ]:
# 3. Function diag:
# The diag function takes two arguments:
# ● An ndarray v.
# ● An integer k (default = 0). If ‘v’ is dimension is 1 then the function constructs a matrix where its diagonal number k 
# is formed by the elements of the vector ‘v’. If a is a matrix (dimension 2) then the function extracts the elements of
# the kth diagonal in a one-dimensional vector.

In [17]:
lsta = [1,4,7,5,2,3]

np_diagalpha = np.diag(lsta)

print(np_diagalpha)

[[1 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 3]]


In [ ]:
np_diag = np.diag(list(range(1,10)))

print(np_diag)

In [ ]:
np_array_1 = np.ones((3,3))


print(np_array_1)

In [19]:
np_num = np.arange(25).reshape(5,5)

print(np_num)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [20]:
np_diag1 = np.diag(np_num)

print(np_diag1)

[ 0  6 12 18 24]


In [ ]:
# Two uses for diagonal function. If supplied a vector(1D array) it will construct a square matrix of shape - len(vector)x
# len(vector) with the vector elements along the diagonal. 

# If supplied a 2D Matrix - will extract the elements along the diagonal.

In [ ]:
np_array_1 = np.diag([1,3,5])
print(np_array_1)

In [ ]:
np_diag1 = np.diag(np_array_1)

print(np_array_1)

In [ ]:
print(np_diag1)

In [ ]:
np_arr_lst = np.array([[1,2,3], [10,20,30], [100,200,300]])

print(np_arr_lst)

In [ ]:
np_diag_l = np.diag(np_arr_lst)

print(np_diag_l)

In [ ]:
np_diag_2 = np.diag(np_arr_lst, -1)

print(np_diag_2)

In [ ]:
import numpy as np

np_ones = np.ones((3,3))

print(np_ones)

In [ ]:
print(dir(np))

In [21]:
#4. Function ‘fromfunction’:
# Construct an array by executing a function over each coordinate. Let’s create a vector-based on its indices.

#myfunct = lambda x,y : x - y

import numpy as np

np_ffunc = np.fromfunction(lambda x,y : x-y, (3,4), dtype=int)

print(np_ffunc)

[[ 0 -1 -2 -3]
 [ 1  0 -1 -2]
 [ 2  1  0 -1]]


In [ ]:
00 01 02 03
10 11 12 13
20 21 22 23

In [ ]:
arr3x3 = np.arange(9).reshape(3,3)

print(arr3x3)

In [ ]:
print(arr3x3[1,2])

In [ ]:
#Remember here that the co-ordinates x,y for each element are as follows:

0,0   0,1   0,2
1,0   1,1   1,2
2,0   2,1   2,2

In [23]:
arr2x3x4 = np.arange(24).reshape(2,3,4)

print(arr2x3x4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [24]:
np_ffuncXY2 = np.fromfunction(lambda x,y,z : x*y+z, (2,3,4))

print(np_ffuncXY2)

[[[0. 1. 2. 3.]
  [0. 1. 2. 3.]
  [0. 1. 2. 3.]]

 [[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]]


In [ ]:
# 0,0,0  0,0,1  0,0,2, 0,0,3
# 0,1,0  0,1,1, 0,1,2, 0,1,3
# 0,2,0, 0,2,1, 0,2,2, 0,2,3

# 1,0,0  1,0,1  1,0,2, 1,0,3
# 1,1,0  1,1,1, 1,1,2, 1,1,3
# 1,2,0, 1,2,1, 1,2,2, 1,2,3



In [ ]:
import numpy as np

np_ffunct_gte = np.fromfunction(lambda x,y : x >= y, (3,3))

print(np_ffunct_gte)

In [ ]:
lst1 = list(range(100))

np_lst1 = np.array(lst1)

print(lst1)

In [ ]:
np_arangelst = np_lst1.reshape(5,4,5)

print(np_arangelst)

In [ ]:
np1 = np_arangelst.reshape(2,5,10)

print(np1)

In [ ]:
np_arange = np.arange(1,21).reshape(2,2,5)


print(np_arange)

In [ ]:
lst1 = list(range(1,10))

print(lst1)

In [ ]:
np1 = np.arange(1, 10, 0.5)

print(np1)

In [ ]:
arr1 = np.arange(6).reshape(2,3)

print(arr1)

In [ ]:
lst1 = list(arr1)

print(lst1)

In [34]:
# arange function

lst1 = list(range(1.1,7.1,0.2))

print(lst1)

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
nprange = np.arange(1.1,7.1,0.2)

print(nprange)

[1.1 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5 3.7 3.9 4.1 4.3 4.5
 4.7 4.9 5.1 5.3 5.5 5.7 5.9 6.1 6.3 6.5 6.7 6.9]


In [36]:
# Aggregation methods:

np_sample = np.arange(24).reshape(2,3,4)

print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
test = list(range(1,20))

In [ ]:
test1 = np.arange(1,5,0.2)

print(test1)

In [37]:
# ● ndarray.sum: Return the sum of the array elements over the given axis.
print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [45]:
print(np_sample.sum(2)) # - With no axis specified, sums all the elements of the array.

[[ 6 22 38]
 [54 70 86]]


In [41]:
new_array = np_sample[0] + np_sample[1]

print(new_array)
print(new_array.shape)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)


In [ ]:
print(np.sum(np_sample, axis = 1))

In [ ]:
print(np.sum(np_sample, axis = 1))

In [ ]:
print(np_sample.sum(axis = 1))

In [ ]:
np_s_a0 = np_sample.sum(0) # - with axis specified sums elements of specified axis or you could say collapses specified axis

print(np_s_a0)
print(np_s_a0.ndim)

In [ ]:
print(np_sample)
print(np_sample.ndim)

In [ ]:
np_s_a1 = np_sample.sum(1)

print(np_s_a1)
print(np_s_a1.ndim)

In [ ]:
np_s_a2 = np_sample.sum(2)

print(np_s_a2)
print(np_s_a2.ndim)

In [52]:
print(np_sample)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [53]:
npcumsum = np_sample.cumsum(1)

print(npcumsum)

[[[ 1  2  3  4]
  [ 6  8 10 12]
  [15 18 21 24]]

 [[13 14 15 16]
  [30 32 34 36]
  [51 54 57 60]]]


In [50]:
# ● ndarray.product: Return the product of the array elements over the given axis.

np_sample = np.arange(1,25).reshape(2,3,4)
print(np_sample)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [48]:
print(np_sample)

[[1 2 3]
 [4 5 6]]


In [51]:
np_prod = np_sample.prod(0)

print(np_prod)

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [ ]:
print(np_sample_2)

In [ ]:
np_prod_0 = np_sample_2.prod(2)

print(np_prod_0)

In [ ]:
np_prod_1 = np_sample_2.prod(1)

print(np_prod_1)

In [ ]:
np_sample_2 = np.arange(120).reshape(2,3,4,5)



In [54]:
np_sample_2 = np.random.randint(1,4,24).reshape(2,3,4)

print(np_sample_2)

[[[1 1 3 2]
  [3 2 1 2]
  [2 2 3 3]]

 [[2 1 2 1]
  [1 2 3 1]
  [1 3 1 3]]]


In [56]:
npcumprod2 = np_sample_2.cumprod(axis = 1)

print(npcumprod)

[[[ 1  1  3  2]
  [ 3  2  3  4]
  [ 6  4  9 12]]

 [[ 2  1  2  1]
  [ 2  2  6  1]
  [ 2  6  6  3]]]


In [55]:
npcumprod = np.cumprod(np_sample_2, axis = 1)

print(npcumprod)

[[[ 1  1  3  2]
  [ 3  2  3  4]
  [ 6  4  9 12]]

 [[ 2  1  2  1]
  [ 2  2  6  1]
  [ 2  6  6  3]]]


In [58]:
np_sample = np.arange(120).reshape(2,3,4,5)
print(np_sample)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [60]:
npflat = np_sample.flatten()

print(npflat)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [ ]:
nprand1 = np.random.randint(1,100,24).reshape(2,3,4)

print(nprand1)

In [ ]:
nprand1flat = nprand1.flatten()

print(nprand1flat)

In [62]:
import numpy as np

np_rand_sample = np.random.randint(1,100,24).reshape(2,3,4)

print(np_rand_sample)

[[[72 46 11 40]
  [81  5 41 64]
  [84 65 48 28]]

 [[14 32  7  6]
  [57 78 75  7]
  [47 53 23 77]]]


In [ ]:
# ● ndarray.max: Return the maximum along the given axis.
# ● ndarray.argmax: Return indices of the maximum values along the given axis

In [63]:
print(np_rand_sample)

[[[72 46 11 40]
  [81  5 41 64]
  [84 65 48 28]]

 [[14 32  7  6]
  [57 78 75  7]
  [47 53 23 77]]]


In [64]:
print(np_rand_sample.max()) #without any axis - maximum of array

84


In [65]:
print(np_rand_sample.flatten())

[72 46 11 40 81  5 41 64 84 65 48 28 14 32  7  6 57 78 75  7 47 53 23 77]


In [66]:
print(np_rand_sample.argmax()) # Index position of maximum number - without any axis > index value of max number (flattened
# array)

8


In [ ]:
print(np_rand_sample.flatten())

In [ ]:
x = np_rand_sample.flatten()

y = np.arange(len(x))

print(x)
print(y)

In [ ]:
max_val = x==95

print(max_val)

In [ ]:
print(max_val.sum())

In [ ]:
print(y[max_val])

In [ ]:
print(np_rand_sample)

In [ ]:
np_rand_sample[0][0]<np_rand_sample[0][1]<np_rand_sample[0][2]
np_rand_sample[1][0]<np_rand_sample[1][1]<np_rand_sample[1][2]

In [67]:
print(np_rand_sample)

[[[72 46 11 40]
  [81  5 41 64]
  [84 65 48 28]]

 [[14 32  7  6]
  [57 78 75  7]
  [47 53 23 77]]]


In [71]:
print(np_rand_sample.max(1)) # with axis 0

[[84 65 48 64]
 [57 78 75 77]]


In [73]:
print(np_rand_sample.argmax(1))

[[2 2 2 1]
 [1 1 1 2]]


In [ ]:
2,3,4

axis 0 - 2 elements of axis 0 it will work on (arithmetic, comparison etc) and axis 0 will collapse. Output 3,4
axis 1 - 3 elements of axis 1 it will work on (arithmetic, comparison etc) and axis 1 will collapse. Output 2,4
axis 2 - 4 elements of axis 2 it will work on (arithmetic, comparison etc) and axis 2 will collapse. Output 2,3


In [ ]:
print(np_rand_sample.argmax(2)) # with axis 0

In [ ]:
print(np_rand_sample) #2 x 3 x 4

In [ ]:
print(np_rand_sample.max(1))
print(np_rand_sample.argmax(1))

In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.max(2))
print(np_rand_sample.argmax(2))

In [ ]:
print(np_rand_sample)

In [ ]:
# ● ndarray.min: Return the minimum along the given axis.
# ● ndarray.argmin: Return indices of the minimum values along the given axis.

In [74]:
print(np_rand_sample.min())
print(np_rand_sample.argmin())
print(np_rand_sample.flatten())

5
5
[72 46 11 40 81  5 41 64 84 65 48 28 14 32  7  6 57 78 75  7 47 53 23 77]


In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.min(0))
print(np_rand_sample.argmin(0))

In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.min(1))
print(np_rand_sample.argmin(1))

In [ ]:
print(np_rand_sample.min(2))
print(np_rand_sample.argmin(2))

In [ ]:
print(dir(np))

In [75]:
# ● ndarray.mean: Returns the average of the array elements along the given axis.

print(np_rand_sample)

[[[72 46 11 40]
  [81  5 41 64]
  [84 65 48 28]]

 [[14 32  7  6]
  [57 78 75  7]
  [47 53 23 77]]]


In [76]:
print(np_rand_sample.mean()) #without axis - mean of all elements.

44.208333333333336


In [ ]:
print(np_rand_sample)

In [77]:
print(np_rand_sample.mean(0))

[[43.  39.   9.  23. ]
 [69.  41.5 58.  35.5]
 [65.5 59.  35.5 52.5]]


In [ ]:
print(np_rand_sample.mean(1))

In [ ]:
print(np_rand_sample.mean(2))

In [ ]:
# ● ndarray.cumsum: Return the cumulative sum of the elements along the given axis.

In [ ]:
import numpy as np

np_rand_sample = np.random.randint(1,10,24).reshape(2,3,4)

In [ ]:
print(np_rand_sample)

In [ ]:
# cumsum

# 1,7,9,12,8,3

# 1,8,17,29,37,40

In [ ]:
print(np_rand_sample.cumsum())

In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.cumsum(0))

In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.cumsum(1))

In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.cumsum(2))

In [ ]:
# ● ndarray.cumprod: Return the cumulative product of the elements along the given axis.

In [ ]:
np_sample_cd = np.random.randint(1,3, 24).reshape(2,3,4)

print(np_sample_cd)

In [ ]:
print(np_sample_cd.cumprod())

In [ ]:
print(np_sample_cd)

In [ ]:
print(np_sample.cumprod(0))

In [ ]:
print(np_sample_cd)

In [ ]:
print(np_sample_cd.cumprod(1))

In [ ]:
print(np_sample_cd.cumprod(2))

In [ ]:
# ● ndarray.var: Returns the variance of the array elements, along the given axis.
# ● ndarray.std: Returns the standard deviation of the array elements along the given axis.

In [ ]:
# # What is Numpy?

# Numerical Python - which allows to work with arrays (homogenous elements in arrays).

# #Functions

# arange in numpy - floats, int, datetime64 
# range in lists - will only take integers.

# #Matrix
# identity, eye, zeros, ones, diagnol, full, 

# min, argmin, max, argmax

# sum, prod


In [83]:
import numpy as np

np_rand_sample = np.random.randint(1,100,24).reshape(2,3,4)

In [84]:
print(np_rand_sample)

[[[84 39 71 78]
  [37 37 80 38]
  [78 29 30 20]]

 [[75 13 92 14]
  [68 63 22 24]
  [37 15 30 52]]]


In [ ]:
print(np_rand_sample.mean(2))

In [ ]:
print(np.mean(np_rand_sample, axis = 0))

In [ ]:
lst1 = [1,7,9,3,5]

np_lst1 = np.array(lst1)

print(np_lst1.var())

In [85]:
print(np_rand_sample)

[[[84 39 71 78]
  [37 37 80 38]
  [78 29 30 20]]

 [[75 13 92 14]
  [68 63 22 24]
  [37 15 30 52]]]


In [ ]:
print(np_rand_sample.sum())

In [86]:
print(np_rand_sample.var(2))

[[ 301.5     341.5     515.6875]
 [1261.25    455.1875  177.25  ]]


In [90]:
print(np_rand_sample.std(2))

[[17.36375535 18.47971861 22.70875382]
 [35.51408171 21.33512362 13.31352696]]


In [ ]:
16 -29 3 10

256 + 841 9 100 = 1206/4

In [91]:
print(301.5**(1/2))

17.363755354185336


In [ ]:
# 1,7,9,3,5

# 5 

# 1-5 = -4 sq
# 7-5 = 2 sq
# 9-5 = 4 sq
# 3-5 = -2 sq
# 5-5 = 0 sq


# 40/5



In [ ]:
print('Standard Deviation : ', np_rand_sample.std())

In [ ]:
print(np_rand_sample)

In [ ]:
print('Variance')
print(np_rand_sample.var())

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std())

In [ ]:
print(np_rand_sample)

In [ ]:
print('Variance')
print(np_rand_sample.var())

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std())

In [ ]:
print('Variance')
print(np_rand_sample.var(2))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(2))

In [ ]:
# Boolean indexing - Using comparative operators to get Boolean values array and then using the array to get the relevant
# info from another array. 

# Revised Axes on numpy arrays. 

# Aggregate functions - 

# sum
# prod
# cumsum
# cumprod
# max, argmax
# min, argmin
# mean
# var
# std

### Data Types for ndarrays

In [ ]:
# The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to
# interpret a chunk of memory as a particular type of data:

In [ ]:
import numpy as np
import sys
np_arr1 = np.array([1,2,3], dtype = 'float16')

In [ ]:
print(np_arr1.dtype)
print(np_arr1)

In [ ]:
np_arr2 = np.array([10,-4,3], dtype = 'int8')

print(np_arr2.dtype)
print(np_arr2)

print(sys.getsizeof(np_arr2[0]))
print(sys.getsizeof(10))

In [ ]:
# Type              Type code           Description
# int8, uint8       i1, u1              Signed and unsigned 8-bit (1byte) integer types
# int16, uint16     i2, u2              Signed and unsigned 16-bit integer types
# int32, uint32     i4, u4              Signed and unsigned 32-bit integer types
# int64, uint64     i8, u8              Signed and unsigned 64-bit integer types
# float16           f2                  Half-precision floating point
# float32           f4 or f             Standard single-precision floating point; compatible with C float
# float64           f8 or d             Standard double-precision floating point; compatible with C double
#                                       and Python float object
# float128          f16 or g            Extended-precision floating point
# complex64,        c8, c16, c32        Complex numbers represented by two 32, 64, or 128 floats respectively
# complex128,
# complex256
# bool              ?                   Boolean type storing True and False values
# object            O                   Python object type; a value can be any Python object
# string_           S                   Fixed-length ASCII string type (1 byte per character); for example, to create a
#                                       string dtype with length 10, use 'S10'
# unicode_          U                   Fixed-length Unicode type (number of bytes platform specific); same specification
#                                       semantics as string_ (e.g., 'U10')

# Note: It’s important to be cautious when using the numpy string_ type, as string data in NumPy is fixed size and may
# truncate input without warning

### Arithmetic with NumPy

In [ ]:
# Arrays Arrays are important because they enable you to express batch operations on data without writing any for loops. 
# NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation
# element-wise:

In [ ]:
np_arr1 = np.array([[1,2,3], [4,5,6]])

np_arr2 = np.array([[2,4,6], [8,10,12]])

print(np_arr1)
print(np_arr2)

In [ ]:
print(np_arr1)

In [ ]:
print(np_arr1*10)

In [ ]:
print(np_arr1 * np_arr2)

In [ ]:
print(np_arr2 - np_arr1)

In [ ]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [ ]:
import numpy as np

np_rand3d = np.arange(1,25).reshape(2,3,4)

print(np_rand3d)

In [ ]:
print(np_arr1)

In [ ]:
print(np_arr1*2)

In [ ]:
print(np_arr1)
print(np_arr2)

In [ ]:
print(np_arr1 * np_arr2)

In [ ]:
print((np_arr1*np_arr2)**1/2)

In [ ]:
# Comparisons between arrays of the same size yield boolean arrays:

In [ ]:
np_arr1 = np.random.randint(1,10,24).reshape(2,3,4)
np_arr2 = np.random.randint(1,10,24).reshape(2,3,4)

In [ ]:
print(np_arr1)
print('-'*125)
print(np_arr2)

In [ ]:
print(np_arr1 < np_arr2)

In [ ]:
arrtest = np.arange(1,11).reshape(2,5)

arrtest

print(arrtest.ndim)
print(arrtest)

In [ ]:
np_arr1 = np.random.randint(1,100,6).reshape(2,3)

np_arr2 = np.random.randint(1,100,6).reshape(2,3)

print(np_arr1)
print(np_arr2)

In [ ]:
np_trufals = np_arr1 > np_arr2

print(np_trufals)

In [ ]:
# Uncommon dimensions arrays are 'broadcast'. E.g.

import numpy as np

# However, broadcasting needs to follow certain rules. 

# Arrays are broadcastable if:

# Arrays have exactly the same shape.

np_arr_so = np.arange(1,7).reshape(2,3)
np_arr_lo = np.arange(10,70,10).reshape(2,3)

print(np_arr_so)
print('-'*125)
print(np_arr_lo)

In [ ]:
print(np_arr_so+np_arr_lo)

In [ ]:
# Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

np_arr_so = np.arange(3).reshape(1,3)
print(np_arr_so)

In [ ]:
print(np_arr_lo)

In [ ]:
print(np_arr_so+np_arr_lo)

In [ ]:
np_arr_lo = np.arange(0,60,10).reshape(2,3)
print(np_arr_lo)

In [ ]:
print(np_arr_so*np_arr_lo)

In [ ]:
arr_lo = np.arange(1,25).reshape(2,3,4)
arr_so = np.arange(1,13).reshape(3,4)

print(arr_lo)

In [ ]:
print(arr_so)

In [ ]:
print(arr_so + arr_lo)

In [ ]:
np_arr_lo = np.arange(0,60,10).reshape(3,2)
np_arr_so = np.arange(2).reshape(1,2)

print(np_arr_lo)
print(np_arr_so)

In [ ]:
print(np_arr_lo*np_arr_so)

In [ ]:
np_arr_so = np.arange(6).reshape(3,2)
np_arr_so

In [ ]:
np_arr_lo = np.arange(0,120,10).reshape(2,2,3)
np_arr_lo

In [ ]:
print(np_arr_so+np_arr_lo)

In [ ]:
# Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated
# property is true.

np_arr_so = np.arange(1,7).reshape(2,3)
print(np_arr_so)

In [ ]:
np_arr_lo = np.arange(1,37).reshape(2,3,2,3)
print(np_arr_lo)

In [ ]:
np_arr_so+np_arr_lo

In [ ]:
np_arr_so = np_arr_so.reshape(2,3)
print(np_arr_so)

In [ ]:
print(np_arr_so*np_arr_lo)

In [ ]:
np_append = np.arange(1,13).reshape(2,2,3)

In [ ]:
np_append1 = np.arange(1,7).reshape(1,2,3)

In [ ]:
print(np_append)
print(np_append1)

In [ ]:
new_np = np_append + np_append1

print(new_np)
print(new_np.shape)

In [ ]:
#add, sub, mul, div, pow, mod

In [ ]:
# However, broadcasting follows certain rules:

# An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly
# 1.

# If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that
# dimension.

# Array with smaller ndim than the other is prepended with '1' in its shape.

# Size in each dimension of the output shape is maximum of the input sizes in that dimension.


In [ ]:
# Arange function in Numpy. Takes 4 arguments

#1. Start - Optional - defaults to 0
#2. Stop - Mandatory
#3. Step - Optional - Defaults to 1 but can take floating point numbers as a step (Unlike built-in range function of Python)
#4. dtype - Optional


np_arr_dec = np.arange(1.1,10.2,0.2)

print(np_arr_dec)

In [ ]:
# arange allows to get range of data - it allows integers, floats and datetime64. 

In [ ]:
lst1 = list(range(1.1,10.2,0.2))

print(lst1)

In [ ]:
# arange can take int, float or datetime64 as input parameters

In [ ]:
range_1 = list(range(1,3,0.1))
print(list(range_1))

In [ ]:
range_2 = list(range(1,3,1))
print(list(range_2))

In [ ]:
# linspace function - returns evenly spaced equidistant number numbers between a specified range.

In [ ]:
range(1,10)

1,2,3,4,5,6,7,8,9 = 9 points with a distance of 1

In [ ]:
# linspace 
linspace(1,10)

1,1.9,2.8,3.7,4.6,5.5,6.4,7.3,8.2,9.1 = distance? but need 10 points between start and stop

In [ ]:
# It takes 7 arguments.

#1. Start - Mandatory
#2. Stop - Mandatory
#3. Num - Optional - Number of samples required between the range/interval. By default set to 50
#4. endpoint - Optional - By default set to true and includes the endpoint(i.e. stop value) - if set to False, returns
# equidistant numbers not including the endpoint/stop value.
#5 retstep - Optional - Default is False. If set to true, returns the samples and the step value (distance between samples)
#6 dtype - Optional - By default datatype will be inferred. However, for int datatype, float will be considered even if 
# start and stop are int.
#7 axis - Optional - By default 0 axis. Only useful in case start and stop are array-like.

In [98]:
arr_lin = np.linspace(1,100, num=100, retstep = True, endpoint=False)

print(arr_lin)

(array([ 1.  ,  1.99,  2.98,  3.97,  4.96,  5.95,  6.94,  7.93,  8.92,
        9.91, 10.9 , 11.89, 12.88, 13.87, 14.86, 15.85, 16.84, 17.83,
       18.82, 19.81, 20.8 , 21.79, 22.78, 23.77, 24.76, 25.75, 26.74,
       27.73, 28.72, 29.71, 30.7 , 31.69, 32.68, 33.67, 34.66, 35.65,
       36.64, 37.63, 38.62, 39.61, 40.6 , 41.59, 42.58, 43.57, 44.56,
       45.55, 46.54, 47.53, 48.52, 49.51, 50.5 , 51.49, 52.48, 53.47,
       54.46, 55.45, 56.44, 57.43, 58.42, 59.41, 60.4 , 61.39, 62.38,
       63.37, 64.36, 65.35, 66.34, 67.33, 68.32, 69.31, 70.3 , 71.29,
       72.28, 73.27, 74.26, 75.25, 76.24, 77.23, 78.22, 79.21, 80.2 ,
       81.19, 82.18, 83.17, 84.16, 85.15, 86.14, 87.13, 88.12, 89.11,
       90.1 , 91.09, 92.08, 93.07, 94.06, 95.05, 96.04, 97.03, 98.02,
       99.01]), 0.99)


In [ ]:
1,100 = 100 points

100-1 / 100 = 

endpoint = True

100-1 / 101

In [ ]:
25 equidistant

1 - 49 = 26 equidistant points. 
1 - 47.08 = 25 equidistant points

In [ ]:
# By default creates 50 equidistant samples / points

In [ ]:
arr_lin10 = np.linspace(0,20,5) # with num of samples specified

print(arr_lin10)

In [ ]:
arr_lin10_noEP = np.linspace(1,20,5, endpoint=False) #No Endpoint included

In [ ]:
print(arr_lin10_noEP)

In [ ]:
arr_lin10_noEP_wRS = np.linspace(1,20,5, endpoint=False, retstep=True) #With array as 1st element and step value as 2nd
                                                                       # element of tuple.
print(arr_lin10_noEP_wRS)
print(type(arr_lin10_noEP_wRS))

In [ ]:
arr_lin10_int = np.linspace(1,20,5, dtype = int) # With dtype specified.
print(arr_lin10_int)

In [ ]:
arr_like_lin10 = np.linspace((1,2), (3,4), 10, axis = 1) # Array like start and stop values.
print(arr_like_lin10)

#Note here that default axis is 0. The equidistant numbers are being added along 0 axis

In [101]:
arr_like_lin10_ax1 = np.linspace((1,2,5), (3,4,10), 10, axis = 1) # with equidistant samples added along axis 1

print(arr_like_lin10_ax1)

[[ 1.          1.22222222  1.44444444  1.66666667  1.88888889  2.11111111
   2.33333333  2.55555556  2.77777778  3.        ]
 [ 2.          2.22222222  2.44444444  2.66666667  2.88888889  3.11111111
   3.33333333  3.55555556  3.77777778  4.        ]
 [ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
   8.33333333  8.88888889  9.44444444 10.        ]]


### Random Module in Numpy

In [ ]:
#Randint to generate a random integer
#np.random.seed(101)

In [ ]:
# test_samples using random

# model

# tried the model with samples from test_samples

# tweaked the model

# test_samples (new)

# tried the model and accuracy is even worse than before.


model = randomvalues --------> How good your model is. ---------> Your model improves

the metrics are saying that model deteriorated.

In [27]:
np.random.seed(42)  

import numpy as np

result = np.random.randint(1,10, 5)
print(result)
# Returns random numbers between specified range and number of values specified in third parameter

[7 4 8 5 7]


In [17]:
# 1 * (10*20/1.75+ log(32) / 100**3 + 20**(1/3)) = result100
# 2 * () = result2
# 3 * () = result3

SyntaxError: cannot assign to operator (3189867808.py, line 1)

In [28]:
print(np.random.randint(1,100, (2,3,4))) # Prints 1 number between 0 and 9 - Start not specified defaults to 0, number not specified 
                             # defaults to 1.

[[[83 87 75 75]
  [88 24  3 22]
  [53  2 88 30]]

 [[38  2 64 60]
  [21 33 76 58]
  [22 89 49 91]]]


In [ ]:
def randomint(start = 0, end = mandatory, 1, 2, 3)

In [32]:
#rand - For random float values between 0 and 1 only.

result = np.random.rand(2,3,4)

print(result)

[[[0.35846573 0.11586906 0.86310343 0.62329813]
  [0.33089802 0.06355835 0.31098232 0.32518332]
  [0.72960618 0.63755747 0.88721274 0.47221493]]

 [[0.11959425 0.71324479 0.76078505 0.5612772 ]
  [0.77096718 0.4937956  0.52273283 0.42754102]
  [0.02541913 0.10789143 0.03142919 0.63641041]]]


In [31]:
result = np.random.uniform(1.5,10.2,(2,3,4))


print(result)

[[[ 6.70172982  9.52030584  2.26988477  3.2050509 ]
  [ 1.89347741  4.33037388  4.88149242  3.86073658]
  [ 8.71001633  4.60375394  3.94413023  6.22145592]]

 [[ 2.72604076  8.47911373  2.1485906  10.08591635]
  [ 8.21852949  3.22882643  1.54804242  8.59451443]
  [ 7.64965889  7.84236236  8.21005202  2.14418847]]]


In [ ]:
print(np.random.rand(3,2,4)) # Can take shape as parameter. Here will return 3 arrays on axis 0, 2 on 1 and 4 on 2

In [34]:
#randn function - returns float values in given shape array from a standard normal distribution i.e. 

# Roughly - 68% of the values will be between -1 to 1
# Roughly - 95% of the values will be between -2 to 2, -2 to -1 and 1 to 2 - 27%
# Roughly - 99.2%  of the values will be between -3 to 3, -3 to -2 and 2 to 3 - 4.2%
# Roughly - 99.7% of the values will be between -4 to 4

# If no shape provided will return a single float value.
import numpy as np

result = np.random.randn(50) 

print(result)

[-0.5297602   0.51326743  0.09707755  0.96864499 -0.70205309 -0.32766215
 -0.39210815 -1.46351495  0.29612028  0.26105527  0.00511346 -0.23458713
 -1.41537074 -0.42064532 -0.34271452 -0.80227727 -0.16128571  0.40405086
  1.8861859   0.17457781  0.25755039 -0.07444592 -1.91877122 -0.02651388
  0.06023021  2.46324211 -0.19236096  0.30154734 -0.03471177 -1.16867804
  1.14282281  0.75193303  0.79103195 -0.90938745  1.40279431 -1.40185106
  0.58685709  2.19045563 -0.99053633 -0.56629773  0.09965137 -0.50347565
 -1.55066343  0.06856297 -1.06230371  0.47359243 -0.91942423  1.54993441
 -0.78325329 -0.32206152]


In [36]:
print((result*15)+100)

[ 92.05359694 107.6990115  101.45616324 114.52967486  89.46920359
  95.0850678   94.1183777   78.04727578 104.44180416 103.91582908
 100.07670185  96.481193    78.76943887  93.69032016  94.85928225
  87.96584096  97.58071433 106.06076285 128.29278852 102.61866719
 103.86325586  98.88331126  71.21843177  99.60229187 100.90345315
 136.94863169  97.11458553 104.52321014  99.47932345  82.46982944
 117.14234222 111.27899549 111.86547921  86.35918818 121.04191466
  78.97223406 108.80285641 132.85683439  85.14195512  91.50553406
 101.49477048  92.44786519  76.74004853 101.02844462  84.06544429
 107.10388646  86.20863649 123.24901608  88.25120061  95.16907726]


In [ ]:
#Uniform
import numpy as np

float_val = np.random.uniform(1,5, (2,3,4))

print(float_val)

In [ ]:
import numpy as np

In [39]:
arr1 = np.arange(17,39)
arr1

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [50]:
#choice - Choose a random number from an array or integer. 

# Takes only one 1D array or an integer as input from which to chose. 

choice = np.random.choice(arr1, 10, replace = False)

print(choice)

[22 35 36 23 26 33 27 24 21 28]


In [51]:
names = ['Yashoda', 'Rohan', 'Rakesh', 'Raghu', 'Mala', 'Jatin', 'Mrinasha', 'Sachin']

chosename = np.random.choice(names, 3, replace = False)
print(chosename)

['Yashoda' 'Sachin' 'Rohan']


In [54]:
chosename = np.random.choice(names, 100, p=[0.40,0.2,0.25,0.10,0.01,0.02,0.02,0.00])

print(chosename)

# Probabilities HAVE to be given for each element in the array. You CAN set the probability to 0 for a particular element
# but value MUST be supplied. 
# Total Probabilities MUST equal 1. 

# 1 = 0.4
# 2 = 0.3
# 3 = 0.3

['Yashoda' 'Yashoda' 'Rakesh' 'Yashoda' 'Yashoda' 'Yashoda' 'Yashoda'
 'Raghu' 'Rakesh' 'Rohan' 'Yashoda' 'Rohan' 'Rohan' 'Yashoda' 'Rohan'
 'Yashoda' 'Rakesh' 'Rakesh' 'Yashoda' 'Yashoda' 'Rakesh' 'Rohan' 'Raghu'
 'Rakesh' 'Yashoda' 'Yashoda' 'Rakesh' 'Yashoda' 'Rohan' 'Raghu' 'Rohan'
 'Yashoda' 'Rakesh' 'Rohan' 'Rohan' 'Raghu' 'Yashoda' 'Jatin' 'Raghu'
 'Yashoda' 'Yashoda' 'Yashoda' 'Yashoda' 'Yashoda' 'Rakesh' 'Yashoda'
 'Yashoda' 'Rakesh' 'Yashoda' 'Rakesh' 'Yashoda' 'Yashoda' 'Rakesh'
 'Rakesh' 'Raghu' 'Rakesh' 'Rakesh' 'Yashoda' 'Yashoda' 'Rakesh' 'Rakesh'
 'Mrinasha' 'Rohan' 'Yashoda' 'Rakesh' 'Yashoda' 'Raghu' 'Raghu' 'Rohan'
 'Rakesh' 'Rakesh' 'Yashoda' 'Raghu' 'Rohan' 'Rakesh' 'Yashoda' 'Raghu'
 'Yashoda' 'Yashoda' 'Raghu' 'Yashoda' 'Yashoda' 'Mala' 'Mala' 'Rohan'
 'Rakesh' 'Rohan' 'Yashoda' 'Yashoda' 'Rakesh' 'Rakesh' 'Rakesh' 'Rakesh'
 'Yashoda' 'Rohan' 'Yashoda' 'Rohan' 'Rohan' 'Raghu' 'Yashoda']


In [ ]:
choice = np.random.choice(10) # If an integer x is specified - treats it as a choice in np.arange(x) i.e from 0 to x-1 e.g.
                              # here - it will choose between 0 to 9.
    
print(choice)

In [ ]:
choice = np.random.choice(arr1, 5) # Size of choice specified.
print(choice)

In [ ]:
# By default - replace parameter is True i.e. if a number has been chosen, it will be put back in the array and has a chance
# to be chosen again. By setting to false - the number is removed from array and wont be chosen again.

arr1 = np.arange(5)

print(arr1)

In [ ]:
x = np.random.choice(arr1, 10, replace = True)

print(x)

In [ ]:
lst1 = []

In [ ]:
for x in range(20):
    lst1.append(np.random.choice(arr1, replace = False))

In [ ]:
print(lst1)

In [ ]:
x = np.random.choice(10, 15, replace = False)

print(x)

In [ ]:
np_arr1 = np.arange(4)

print(np_arr1)

In [ ]:
np.random.choice(np_arr1, 4,replace = False)




In [60]:
print(np.random.choice(100,10))

[ 8 49 26 65  4 28 36 37 82  7]


In [ ]:
# 0 = 10%
# 1 = 15%
# 2 = 20%
# 3 = 55%

In [ ]:
print(np_arr1)

In [ ]:
arr1 = [0,1,2,3]

In [ ]:
a = [0.1, 0.15,0.20,0.55]

In [ ]:
print(np_arr1)

In [ ]:
# The p parameter takes probabilities i.e. if I had numbers 1 to 5 - in a uniform distribution each would have a 20% chance
# or (0.2 probability). However, if we were to specify the probabilities, it will take those probabilities into account
# while generating random numbers

choice = np.random.choice(2, p = [0.5,0.5], size = 20)

print(choice)

In [ ]:
x = np.arange(10)

print(x)

In [64]:
#permutation - Returns a random permutation of input array or if integer specified random permutation of np.arrange(integer)

import numpy as np

np.random.seed(42)

perm = np.random.permutation(10)

print(perm)

[8 1 5 0 7 2 9 4 3 6]


In [65]:
np_arr = np.arange(20,40)

print(np_arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [66]:
perm = np.random.permutation(np_arr)

print(perm)

[28 33 29 26 20 31 36 37 32 34 21 24 25 22 35 27 23 39 30 38]


In [68]:
np_arr2 = np_arr.reshape(5,2,2)

print(np_arr2)

[[[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]

 [[32 33]
  [34 35]]

 [[36 37]
  [38 39]]]


In [ ]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

In [71]:
print(np_arr2)

[[[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]

 [[32 33]
  [34 35]]

 [[36 37]
  [38 39]]]


In [70]:
perm_arr = np.random.permutation(np_arr2) #
print(perm_arr)


# For a multidimensional array - it is only shuffled along the 0 index axis.

[[[36 37]
  [38 39]]

 [[28 29]
  [30 31]]

 [[24 25]
  [26 27]]

 [[20 21]
  [22 23]]

 [[32 33]
  [34 35]]]


In [ ]:
perm_reshape = np.arange(24).reshape(2,3,4)

print(perm_reshape)

In [ ]:
perm_arr1 = perm_arr.flatten()

perm_arr2 = np.random.permutation(perm_arr1).reshape(4,3,2)

print(perm_arr2)

In [ ]:
perm_reshape = perm_reshape.reshape(4,3,2)

print(perm_reshape)

In [ ]:
perm_reshape2 = np.random.permutation(perm_reshape).reshape(2,3,4)

print(perm_reshape2)

In [72]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#any - Returns true if any of the elements in the array are true. 
#all Returns true if all of the elements in the array are true.

In [ ]:
print(arr)

In [73]:
print(np.any(arr))

True


In [74]:
print(np.all(arr))

False


In [ ]:
print(arr.all())

In [ ]:
print(arr.any())

In [ ]:
print(dir(np))

In [ ]:
print(dir(arr))

In [75]:
arr_zero = np.zeros(5)

print(arr_zero)

[0. 0. 0. 0. 0.]


In [79]:
print(np.any(arr_zero))

True


In [80]:
print(np.all(arr_zero))

False


In [78]:
arr_zero[2] = 100

print(arr_zero)

[  0.   0. 100.   0.   0.]


In [ ]:
arr_alt = np.random.randint(0,2,5)

print(arr_alt)

In [ ]:
print(np.any(arr_alt))

In [ ]:
print(np.all(arr_alt))

In [81]:
arr_zero_grid = np.zeros((2,3))
print(arr_zero_grid)

[[0. 0. 0.]
 [0. 0. 0.]]


In [83]:
arr_zero_grid[1,0] = 100

print(arr_zero_grid)

[[  0.   0.   0.]
 [100.   0.   0.]]


In [86]:
print(np.any(arr_zero_grid, axis = 0))

[ True False False]


In [88]:
print(np.all(arr_zero_grid, axis = 0))

[False False False]


In [ ]:
arr_one_grid = np.ones((2,3))
print(arr_one_grid)

In [ ]:
print(np.any(arr_one_grid))

In [ ]:
print(np.all(arr_one_grid))

In [1]:
import numpy as np


arr = np.arange(11)
arr10 = np.arange(11,21)
print(arr)
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [2]:
# Append

arr_n_10 = np.append(arr, arr10)
print(arr_n_10)

print(arr)
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
lst1 = [1,2,3,4]
x = lst1.append(5)

print(x)
print(lst1)

In [3]:
arr_1 = np.arange(1,11).reshape(2,5)
arr_2 = np.arange(21,31).reshape(2,5)
arr_3 = np.arange(101,251,10).reshape(3,5)
print(arr_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
print(arr_2)

[[21 22 23 24 25]
 [26 27 28 29 30]]


In [6]:
# arr_x = np.append(arr_1, arr_2)

# print(arr_x)

[ 1  2  3  4  5  6  7  8  9 10 21 22 23 24 25 26 27 28 29 30]


In [5]:
print(arr_3)

[[101 111 121 131 141]
 [151 161 171 181 191]
 [201 211 221 231 241]]


In [ ]:
arr_1n2 = np.append(arr_1, arr_3, axis = 1)

print(arr_1n2)

In [ ]:
#[[1,2,3,4,5]
#[6,7,8,9,10]
#[[21,22,23,24,25]
#[26,27,28,29,30]]



In [ ]:
arr_1n2V = np.append(arr_1, arr_2, axis = 0)

print(arr_1n2V)

In [ ]:
#vstack - stacks arrays vertically

arr_V = np.vstack((arr_1, arr_2))
print(arr_V)

In [ ]:
arr1x = np.arange(1,6)
arr2x = np.arange(11,16)
print(arr1x)
print(arr2x)

In [ ]:
arr_vx = np.vstack((arr1x, arr2x))
print(arr_vx)


In [ ]:
arr1x = np.arange(1,13).reshape(2,2,3)
arr2x = np.arange(11,23).reshape(2,2,3)
print(arr1x)

In [ ]:
print(arr2x)

In [ ]:
arrvx = np.vstack((arr1x,arr2x))

print(arrvx)

In [ ]:
print(arr1x)

In [ ]:
print(arr2x)

In [ ]:
arr1x = np.arange(6).reshape(2,3)
arr2x = np.arange(10,16).reshape(2,3)


print(arr1x)
print(arr2x)

In [ ]:
print(dir(np))

In [ ]:
arr_H = np.hstack((arr1x, arr2x))

print(arr_H)

In [ ]:
arr1x = np.arange(1,13).reshape(2,2,3)
arr2x = np.arange(11,17).reshape(2,3)
print(arr1x)

In [ ]:
print(arr2x)

In [ ]:
arr_2n3 = np.append(arr_1,arr_2, axis = 1)

print(arr_2n3)

In [ ]:
arr1 = np.arange(24).reshape(2,3,4)
arr2 = np.arange(0,240,10).reshape(2,3,4)

print(arr1)
print(arr2)

In [ ]:
arr12hstack = np.hstack((arr1,arr2))

print(arr12hstack)

In [ ]:
arr12vstack = np.vstack((arr1, arr2))

print(arr12vstack)

In [ ]:
#sort will by default sort on the last axis.
np.random.seed(101)
arr_rand = np.random.randint(1,10, 20).reshape(2,2,5)
print(arr_rand)

In [ ]:
arr_sort = np.sort(arr_rand, axis = 1)
print(arr_sort)

In [ ]:
print(arr_rand)

In [ ]:
0,1,2,3, 4,5,6

-7,-6,-5,-4,-3,-2,-1

In [ ]:
0,1,2
-3,-2,-1

In [ ]:
arr_sort = np.sort(arr_rand, axis = -2) 
print(arr_sort)

In [ ]:
# insert

print(arr_sort)

In [ ]:
arr_sort = np.arange(10,100,10)

print(arr_sort)

In [ ]:
1

In [ ]:
arr_ins = np.insert(arr_sort,2, 555)

print(arr_ins)

In [ ]:
arr_ins2 = np.insert(arr_sort, -1,555)


print(arr_ins2)

In [ ]:
import numpy as np

arr_sort = np.arange(1,31).reshape(6,5)
print(arr_sort)

In [ ]:
arr3d = np.random.randint(1,10,24).reshape(2,3,4)

print(arr3d)

In [ ]:
arrins = np.random.randint(1,5,12).reshape(3,4)

print(arrins)

# 2 x 3 x 4

In [ ]:
print(arr3d)

In [ ]:
arrIns = np.arange(100,106).reshape(2,3)

In [ ]:
arroutput = np.insert(arr3d, 1, arrins, axis = 0)


print(arroutput)

In [ ]:
print(arr3d)

In [ ]:
arrins1 = np.arange(8).reshape(2,4)

print(arrins1)

In [ ]:
arrinsX1 = np.insert(arr3d,1, arrins1, axis = 1)

print(arrinsX1)

In [ ]:
arrins2 = np.arange(6).reshape(2,3)

print(arrins2)

In [ ]:
print(arr3d)

In [ ]:
print(arr3d)

print(arrins2)

In [ ]:
arrinsX2 = np.insert(arr3d, 2, arrins2, axis = 2)

print(arrinsX2)

In [ ]:
arrins2 = np.arange(101,107).reshape(2,3)

print(arrins2)

In [ ]:
print(arr3d)

In [ ]:
2,3,4   = Axis 0 has 2 elements of (3x4)   = 3x4

2,3,4 = Axis 1 has 3 elements of 1d arrays = 2 x 4

2,3,4 = Axis 2 has 4 elements along it = 2x3

In [ ]:
arr_result = np.insert(arr3d,1,arrins2,axis=2)

print(arr_result)

In [ ]:
arr3d = np.arange(48).reshape(4,3,4)

print(arr3d)

In [ ]:
arrIns = np.arange(10,121,10).reshape(3,4)

print(arrIns)

In [ ]:
arr_ins = np.insert(arr3d, [1,3], arrIns, axis=0)

print(arr_ins)

In [ ]:
print(arr_sort)

In [ ]:
arr_ins1 = np.insert(arr_ins, 4, [1,1,1,1,1,1], axis = 0)

print(arr_ins1)

In [ ]:
print(arr_ins)

In [ ]:
arr_ins[0][1] = 20

print(arr_ins)
print(arr_sort)

In [ ]:
print(arr_ins)

In [ ]:
arr_flat = arr_ins.flatten()
print(arr_flat)

In [ ]:
arr_flat_ins = np.insert(arr_flat, 4, 20)

print(arr_flat_ins)

In [ ]:
#Transpose

In [ ]:
arr_1 = np.arange(1,9).reshape(2,4)

print(arr_1)

In [ ]:
arr2 = arr_1.transpose() #Returns only a view of the transposed array and does not have a inplace parameter - so to see
# the effect - must save the transposed view to a variable.

print(arr2)

In [ ]:
print(arr_1)
print(arr2)

In [ ]:
arr2[-1,-1] = 888

print(arr_1)
print(arr2)

In [ ]:
0,1

1,0


In [ ]:
arr_2[2][3] = 777

arr_2

In [ ]:
arr_1

In [ ]:
import copy

arr_3 = copy.deepcopy(arr_1.transpose())

In [ ]:
arr_3

In [ ]:
arr_3[0][0] = 1000

arr_3

In [ ]:
arr_1

In [ ]:
arr_1 = np.arange(1,25).reshape(2,3,4)

print(arr_1)

In [ ]:
#0,1,2  = 2,3,4

#1,0,2 = 3,2,4

arr_2 = np.transpose(arr_1, (1,0,2))

print(arr_2)
arr_2.shape

In [ ]:
print(arr_1) # 2 x 3 x 4

In [ ]:
arr_3 = np.transpose(arr_1, (1,2,0))

print(arr_3)

# 3 x 4 x 2

In [ ]:
print(arr_3)

In [ ]:
print(arr_1)

In [ ]:
arrtransp = np.transpose(arr_1, (2,1,0))

print(arrtransp)

In [ ]:
np_arr1 = np.arange(1,21).reshape(4,5)

np_arr2 = np.arange(1,201,10).reshape(5,4)

print(np_arr1)

In [ ]:
print(np_arr2)

In [ ]:
np.dot(np_arr1,np_arr2)

In [ ]:
print(dir(np))

In [ ]:
print(1 

### Datetime

In [ ]:
# Numpy has a datetime64 function which converts string with input 'YYYY-MM-DD hh:mm:ss.ms' format to a datetime object. 
# Unlike the string, we can perform arithmetic operations on datetime objects (and in some cases require the help of the 
# timedelta24 object - more on that later).

In [ ]:
import numpy as np

np_date = np.datetime64('2023-04-08')

print(np_date)
print(type(np_date))

In [ ]:
#YYYY-MM-DD hh:mm:ss.ms

#YYYY
#YYYY-MM
#YYYY-MM-DD hh:mm:ss.ms

In [ ]:
print(np_date+7)

In [ ]:
print(type(np_date))

In [ ]:
print(np_date.dtype)

In [ ]:
# We can also input a partial string if we do not wish the complete date (including timestamp)

In [ ]:
np_msecs = np.datetime64('2022-09-16 11:20:45.09')

print(np_msecs)

In [ ]:
np_msecs.dtype

In [ ]:
# Note how a 'T' denoting time has been inserted between the date and the time.

In [ ]:
np_secs = np.datetime64('2022-09-16 11:20:45')

print(np_secs)

In [ ]:
np_mins = np.datetime64('2022-09-16 11:20')

print(np_mins)

In [ ]:
np_hours = np.datetime64('2022-09-16 11')

print(np_hours)

In [ ]:
np_days = np.datetime64('2022-09-16')

print(np_days)

In [ ]:
np_mths = np.datetime64('2022-09')

print(np_mths)

In [ ]:
np_years = np.datetime64('2022')

print(np_years)

In [ ]:
# The datetime64 function can take an additional parameter - The abbreviate of the time unit.

In [ ]:
np_dtime = np.datetime64('2022-09-12 11:20', 'M')

print(np_dtime)
print(np_dtime.dtype)

In [ ]:
np_dtime2 = np.datetime64('2023-04-12', 'W')

print(np_dtime2)

In [ ]:
# Common abbreviations are givin below

# Abbreviation - Meaning
# Y            - Years
# M            - Months
# D            - Days
# W            - Weeks
# h            - Hours
# m            - Minutes
# s            - Seconds




In [ ]:
print(np_dtime+1)

In [ ]:
today = np.datetime64('today')

print(today)

In [ ]:
np_weeks = np.datetime64('2023-04-20', 'D')

print(np_weeks)
print(np_weeks.dtype)

In [ ]:
print(np_weeks-72)

In [ ]:
# Another useful input that the datetime64 function can take is 'today' giving the current date

In [ ]:
np_today = np.datetime64('today', 'm')

print(np_today)
print(np_today.dtype)

In [ ]:
print(np_today+1)

In [ ]:
np_tod_mth = np.datetime64('today', 'M')

print(np_tod_mth-4)

In [ ]:
# However, what if we wanted to add 4 months to today? If we added +4 to my day datatype datetime64 object it would add 4 
# days to my date and not months. To do this kind of arithmetic on dates, we have the timedelta64 object. 

In [ ]:
np_hours = np.datetime64('today','m')

print(np_hours)

In [ ]:
npnew = np_hours + np.timedelta64(5,'D')

print(npnew)

In [ ]:
nptd64 = np.timedelta64(5,'D')

print(nptd64)
print(type(nptd64))
print(nptd64.dtype)

In [ ]:
print(np_add_day)

In [ ]:
np_add_day = np_hours + np.timedelta64(3, 'Y')

print(np_add_day)

In [ ]:
np_year = np.datetime64('today', 'M')

print(np_year)

In [ ]:
np_year_add = np_year + np.timedelta64(3,'Y')

print(np_year_add)

In [ ]:
# TimeDelta64 - Does not work between datetime64 object of unit day(or lower) and Year/Month timedelta64

In [ ]:
np_tod_mth = np.datetime64('today', 'M')

print(np_tod_mth)

In [ ]:
np_tod_day = np_tod_mth + np.timedelta64(1, 'Y')

print(np_tod_day)

In [ ]:
np_days_tobday = np.datetime64('2023-08-04') - np.datetime64('today')

print(np_days_tobday)
print(np_days_tobday.dtype)
print(type(np_days_tobday))

In [ ]:
# However, due to the fact that length of months and also of years are non-standard i.e. a year can have either 365 or 366
# days and months can have either 30,31, 28 or 29 days - timedelta64 does not work between day type and month / year 
# timedelta64. 

In [ ]:
np_addtime = np.datetime64('today', 'm')

print(np_addtime)

In [ ]:
print(np_addtime+np.timedelta64(3, 'Y'))

In [ ]:
np_addmths = np.datetime64('today')+ np.timedelta64(4, 'M')

print(np_addmths)

In [ ]:
np_addmths = np.datetime64('today', 'M')+ np.timedelta64(4, 'M')

print(np_addmths)

In [ ]:
print(np.datetime64('2022-12','D'))

In [ ]:
# For the above example, would have no choice but to truncate to the desired time unit, then add back the days. 

# For example - 4 months from today

add_days = np.datetime64('2022-12-05 13:10','m')-np.datetime64('today', 'M')

print(add_days)
print(add_days.dtype)


In [ ]:
add_4mths = np.datetime64('today', 'M') + np.timedelta64(4,'M')+add_days

print(add_4mths)

In [ ]:
# Or simply

In [ ]:
add_4mths2 = np.datetime64('today', 'M') + 4+add_days

print(add_4mths2)

In [ ]:
# But if we wanted to add a year to today we could do:

add_1yr = np.datetime64('today', 'M') + np.timedelta64(1,'Y') + add_days

print(add_1yr)

In [ ]:
np_today = np.datetime64('today', 'm')

print(np_today)

In [ ]:
print(np.datetime64('today', 'M'))

In [ ]:
np_adddays = np_today - np.datetime64('today', 'M')

print(np_adddays)

In [ ]:
np_add4months = np.datetime64('today', 'M') + np.timedelta64(4,'M') + np_adddays

In [ ]:
print(np_add4months)

In [ ]:
# is_busday function

In [ ]:
np_isbusday = np.is_busday(np.datetime64('2023-04-23'), weekmask = [1,1,1,1,1,0,0])

print(np_isbusday)

In [ ]:
# weekmask = [1,1,1,1,1,0,0]
# weekmask = '1111110'
#weekmask = 'Mon Tue Wed Thu Fri Sat'

In [ ]:
#weekmask in busday functions

np_isbusday = np.is_busday(np.datetime64('2022-12-10'), weekmask = weekmask)

print(np_isbusday)

In [ ]:
today = np.datetime64('2022-11-01', 'D')

print(today)

In [ ]:
aprdates = np.arange('2023-04-01', '2023-05-01', dtype = 'datetime64[D]')

print(aprdates)
print(type(aprdates[0]))
print(aprdates[0].dtype)

In [ ]:
arr1 = np.arange(1,100)

print(arr1%2 == 0)

In [ ]:
satsunNov = np.is_busday(aprdates, weekmask = '0000011')

print(satsunNov)

In [ ]:
print(aprdates[satsunNov])

In [ ]:
#busday_count

busday_count = np.busday_count('2023-04-01', '2023-05-01')

print(busday_count)




In [ ]:
import numpy as np

In [ ]:
#busday_offset

busday_offset = np.busday_offset('2023-04-20',2)

print(busday_offset)

https://numpy.org/doc/stable/reference/arrays.datetime.html

In [ ]:
import numpy as np
x= np.random.randint(1,10,9).reshape(3,3)
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

In [ ]:
# Numpy

1. Its a library which helps us work with arrays in Python and does numerical processing very fast.
2. Arrays are homogenous datatypes.

# Creating arrays - 
1. Through np.array or np.asarray and the difference. 
2. Multidimensional arrays and relationship with axis number. 
3. Attributes of a numpy array i.e. dtype, shape, ndim.


In [ ]:
#Methods we say Nov 8, 2022

array and asarray - along with difference. 

zeros
ones
empty
full
identity
eye
diag

zerolike, onelike, fulllike, emptylike

arange
reshape

flatten
fromfunction
prod
sum
min
argmin
max
argmax


What is numpy?

Numpy is a module in python that allows us to work with arrays. 
It stands for numerical python. 


arrays - are multidimensional sequences containing homogenous datatypes. Arrays are mutable. 

Advantages of arrays over the native python datatypes?
1. Faster processing of arrays - since arrays store the data in contiguous blocks of memory and are homogenous, the metadata
is contained in the array object itself allowing for faster access to the data and therefore faster processing. 
2. Operations can be performed on arrays quickly without the use of a for loop. 
3. Easier transfer between algorithms and scripts. 

Indexing and slicing in arrays, boolean indexing in arrays

array, asarray - and difference between these two. 

Broadcasting and operations between arrays. 

Array axes, shapes and dimensions.



In [ ]:
import numpy as np

arr1 = np.arange(120)