In [14]:
import numpy as np
array1=np.arange(24).reshape(2,3,4)
print(array1)
print(('-')*15)
print(array1[[0,1],[2,1],[1,3]])
# array1[[1, 2]] = array1[[2, 1]]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
---------------
[ 9 19]


In [16]:
# Sankara

arrayS = np.arange(24).reshape(2,3,4)

x = arrayS[0,:,:1]
y = arrayS[0,:,0]

print(arrayS)
print(x)
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[0]
 [4]
 [8]]
[0 4 8]


In [ ]:
# Normalise data. Means to scale the values such that your values fall between 0 and 1. 

# 7,21,42,33,82 = 0 to 1

# 7/82, 21/82, 42/82, 33/82, 82/82 

# grading on a curve?


In [ ]:
# 2021

# Physics exam - The exam for 2021 was much easier than the exam for 2022

96/96 = 100% = 1

89/96 = 93~94%

# 2022

# Physics exams

# 93/93 = 100%

# 84/93 = 95%

In [25]:
arrayG = np.arange(24).reshape(2,3,4)

# 0,1,2,3
# 0,1,2
# 0,1
# 0
print(arrayG)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
arrayG[1,1:,1:3]

array([[17, 18],
       [21, 22]])

In [29]:
arr = np.arange(11)
arr_slice = arr[5:8].copy()
print(arr)
print(arr_slice)
arr[6] = 686

print(arr)
print(arr_slice)



[ 0  1  2  3  4  5  6  7  8  9 10]
[5 6 7]
[  0   1   2   3   4   5 686   7   8   9  10]
[5 6 7]


In [ ]:
#0,1,2,3,4

In [33]:
# Broadcasting

np.random.seed(42)

arrayY = np.random.randint(1,11,24).reshape(2,3,4)

print(arrayY)

[[[ 7  4  8  5]
  [ 7 10  3  7]
  [ 8  5  4  8]]

 [[ 8  3  6  5]
  [ 2  8  6  2]
  [ 5  1 10  6]]]


In [49]:
np.random.seed(101)

arrayYM = np.random.randint(1,11,12).reshape(1,1,3,4)

print(arrayYM)

[[[[ 2  7  8 10]
   [ 9  5  9  6]
   [ 1  6  9  2]]]]


In [34]:
arrayY2 = arrayY*2 

print(arrayY2)

[[[14  8 16 10]
  [14 20  6 14]
  [16 10  8 16]]

 [[16  6 12 10]
  [ 4 16 12  4]
  [10  2 20 12]]]


In [37]:
print(arrayY.shape)
print(arrayYM.shape)

(2, 3, 4)
(2, 3, 4)


In [44]:
arrayY3 = arrayY+arrayYM

print(arrayY3)

[[[ 9 11 16 15]
  [ 9 17 11 17]
  [10 12 12 18]]

 [[17  8 15 11]
  [11 13 15  8]
  [14  6 19 12]]]


In [ ]:
# For broadcasting two arrays, either the no of elements on respective dimensions must be the same or must be one element.
# If the shape of smaller array is shorter than bigger array, each missing dimension on shorter array will be prepended with 
# 1. 

In [ ]:
vstack = append(0 axis)
hstack = append(1 axis)